### ISSUE TITLE
Known bugs and wishes that need help

### ISSUE THREAD

**Issue by eribertomota** [axel-download-accelerator/axel#18]
The intent of this bug is help the people that wants help to solve the known bugs in Axel. Please, choose a bug and send us a pull request. Thanks!
#### Bugs:
- [x] Implement SSL #3. This is a bug because makes SSL downloads impossible to be done and generates a 'Too many redirects' message. (work being done by @sdt)
#### Wishes
- [ ] Add socks5 support enhancement #2
- [ ]  Add unit testing #5 
- [x]  File name from Content-Disposition header #8 
#### Bugs:
- [x] Segmentation fault when using user:pass in FTP (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=645234)
- [x] Segmentation fault when we execute it with a connection negative values (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=703453)
- [x] Segmentation fault when redirecting from HTTP to FTP (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=449513#43)
#### Wishes
- [ ] Support .netrc files (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=127074)

#### Bugs:
- [x] Too many redirects. Segmentation fault. The same issue related at #3. (https://bugs.launchpad.net/ubuntu/+source/axel/+bug/253906)
#### Wishes
- [ ] Flashgot+axel not working properly (https://bugs.launchpad.net/ubuntu/+source/axel/+bug/899867)
- [x] Proxy authentication (maybe implemented in Fedora) (https://bugs.launchpad.net/ubuntu/+source/axel/+bug/922963)
#### Wishes:
- [x] Patch to allow authentication behind proxy (https://bugzilla.redhat.com/show_bug.cgi?id=675964)

**Comment by sijad** [comment]
I guess https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=703453 has been fixed

**Comment by eribertomota** [comment]
Hi @sijad.

You are right. Fixed in 2.7 version. I will close the bug. Thanks!

Cheers,

Eriberto

**Comment by ordex** [comment]
@eribertomota @ismaell I think we should close this ticket and open as many as needed for each single problem. Right now, we don't have any ticket for:
- Support .netrc files (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=127074)
- Flashgot+axel not working properly (https://bugs.launchpad.net/ubuntu/+source/axel/+bug/899867)

shall we open one each?

The others are already tracked in their own tickets.

**Comment by eribertomota** [comment]
2017-09-25 0:17 GMT-03:00 Antonio Quartulli <notifications@github.com>:

> @eribertomota <https://github.com/eribertomota> @ismaell
> <https://github.com/ismaell> I think we should close this ticket and open
> as many as needed for each single problem. Right now, we don't have any
> ticket for:
>
>    - Support .netrc files (https://bugs.debian.org/cgi-
>    bin/bugreport.cgi?bug=127074)
>    - Flashgot+axel not working properly (https://bugs.launchpad.net/
>    ubuntu/+source/axel/+bug/899867
>    <https://bugs.launchpad.net/ubuntu/+source/axel/+bug/899867>)
>
> shall we open one each?
>

Done!

Cheers,

Eriberto

**Comment by ordex** [comment]
Nice thanks! @eribertomota can we close this now?

**Comment by eribertomota** [comment]
2017-09-25 9:48 GMT-03:00 Antonio Quartulli <notifications@github.com>:

> Nice thanks! @eribertomota <https://github.com/eribertomota> can we close
> this now?
>

I think that yes. Can you close?

**Comment by ordex** [comment]
Sure
